### ISSUE TITLE
FID cannot be passed via Web GUI

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs20-nsg#3]
As the NSG profile based on the WFS 2.0 specification, the test invokeGetFeatureById is executed. This test requires a feature id of a feature provided by the tested services. The fid is passed via parameter and should be entered in the main form if the web GUI  is used (as in ETS WFS 2.0). Currently this form element is missing and the test fails.

**Comment by lgoltz** [comment]
Fixed with #6 
FIS is documented as mandatory, as it is required for conformance class  NSG Basic WFS.

**Comment by dstenger** [comment]
Fix solves the problem and was tested successfully.
