### ISSUE TITLE
Count default test compares a string with an integer

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20-nsg#4]
Seeing this failure:

"java.lang.AssertionError: A value of 10 for constraint CountDefault is expected expected <br><br>[10] but found <br><br>[10]"

I've checked the code, it seems it's comparing a string with an integer, and thus always failing:

https://github.com/opengeospatial/ets-wfs20-nsg/blob/c3885eeaa04adce6cef0958a8b22951546086526/src/main/java/org/opengis/cite/wfs20/nsg/testsuite/getfeature/CountParameter.java#L47

**Comment by dstenger** [comment]
Fix solves the problem and was tested successfully.
